version: "3"
services:
  frontend:
    image: developaul/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  nginx:
    restart: always
    image: developaul/docker-nginx
    ports:
      - "3000:80"
  backend:
    image: developaul/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app